Install Ginkgo 1.4.0 during integration tests
When performing integration tests, Ginkgo is installed using `go get`. At the
time of writing, it appears a new version of Ginkgo has been released which
causes an error like below

```
go get -u github.com/onsi/ginkgo/ginkgo
../../onsi/ginkgo/ginkgo/outline/outline.go:91:8: undefined: strings.Builder
```

The version of Ginkgo being used in `go.mod` is 1.4.0, so the Makefile should
install the same version.